version: '3'

services:
# HAPROXY used to host servers to outside world
  proxy:
    build: ./services/proxy
    image: devpaul-haproxy
    ports:
      - "8080:80"
#      - "8443:443"
    depends_on:
      - devpaul-static
      - devpaul-certbot
# DevPaul build process for the static site
# Separate build container builds into the devpaul-code volume to remove (node) dependencies from the nginx container
  devpaul-build:
    build: packages/static-site/Dockerfile.build
    volumes:
      - devpaul-code:/srv/_dist
# Static nginx site
  devpaul-static:
    image: nginx
    expose:
      - "80"
    depends_on:
      - devpaul-build
    volumes:
      - devpaul-code:/usr/share/nginx/html
# Certbot
  devpaul-certbot:
    image: certbot/certbot
    command: certonly --standalone -d devpaul.com \
      --preferred-challenges http --http-01-port 80
      --non-interactive --agree-tos --email paul@devpaul.com
    expose:
      - "8888"
    volumes:
      - devpaul-cert:/var/www
volumes:
  devpaul-code:
  devpaul-cert:

