version: '3'

services:
  # Static nginx site
  devpaul-static:
    image: nginx:stable
    expose:
    - "80"
    depends_on:
    - devpaul-build-site
    volumes:
    - devpaul-code:/usr/share/nginx/html

